HaveFun_03/Models/ErrorViewModel.cs
namespace HaveFun_03.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HaveFun_03/Controllers/HomeController.cs
using HaveFun_03.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HaveFun_03.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HaveFun_03/Controllers/TIM00Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM00Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/TIM01Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM01Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/TIM02Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM02Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/TIM03Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM03Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/TIM05Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM05Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/TIM06Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM06Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/TIM07Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM07Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/TIM08Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class TIM08Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Controllers/Tim04Controller.cs
using Microsoft.AspNetCore.Mvc;

namespace HaveFun_03.Controllers
{
    public class Tim04Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

HaveFun_03/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HaveFun_03/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HaveFun_03</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HaveFun_03.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HaveFun_03</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TIM04" asp-action="Index">TIM04</a>
                        </li>
                        <li class="nav-item">ggg

                            <a class="nav-link text-dark" asp-area="" asp-controller="TIM02" asp-action="Index">TIM02</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="TIM00" asp-action="Index">TIM00</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TIM08" asp-action="Index">TIM08</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TIM06" asp-action="Index">TIM06</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TIM03" asp-action="Index">TIM03</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HaveFun_03 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HaveFun_03/Views/TIM00/Index.cshtml
<input type="file" />

<button>上傳</button>

@section Scripts {
    <script>
        const input = document.querySelector('input[type="file"]');

        document.querySelector("button").addEventListener("click", () => {
            const file = input.files[0];
            const fileReader = new FileReader();

            fileReader.addEventListener("load", (event) => {
                const base64Str = event.target.result.split(",")[1];

                fetch("/fileUpload", {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                        file: base64Str
                    })
                })
                    .then(response => {
                        // Handle the response from the server
                        console.log(response);
                    })
                    .catch(error => {
                        // Handle any errors that occurred during the request
                        console.error(error);
                    });
            });

            fileReader.readAsDataURL(file);
        });
    </script>
}

HaveFun_03/Views/TIM01/Index.cshtml
TIM01

HaveFun_03/Views/TIM02/Index.cshtml
@{
    ViewData["Title"] = "Geolocation Booking";
}

<title>@ViewData["Title"]</title>
<head>
    <script>
        function getLocation() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(successCallback, errorCallback);
            } else {
                alert("Geolocation is not supported by this browser.");
            }
        }

        function successCallback(position) {
            const latitude = position.coords.latitude;
            const longitude = position.coords.longitude;
            const url = getGoogleMapsUrl(latitude, longitude);
            console.log(`Success: Latitude: ${latitude}, Longitude: ${longitude}, URL: ${url}`);

            // Store latitude and longitude in localStorage
            localStorage.setItem('latitude', latitude);
            localStorage.setItem('longitude', longitude);

            // Display latitude, longitude, and URL link on the webpage
            const locationInfo = document.createElement('div');
            locationInfo.innerHTML = `Latitude: ${latitude}<br>Longitude: ${longitude}<br><a href="${url}" target="_blank">Open in Google Maps</a>`;
            document.body.appendChild(locationInfo);
        }

        function errorCallback(error) {
            console.log("Error: ", error);
            alert(`Error retrieving geolocation: ${error.message}`);
        }

        function getGoogleMapsUrl(latitude, longitude) {
            const baseUrl = 'https://www.google.com.tw/maps/';
            const query = `@@${latitude},${longitude},15z`;
            const params = {
                entry: 'ttu'
            };
            const paramsString = new URLSearchParams(params).toString();
            return `${baseUrl}${query}?${paramsString}`;
        }
    </script>
</head>
<body onload="getLocation()">
    <h1>TIM02</h1>
    <div class="access_map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d105111.88622656197!2d-58.526502463231886!3d-34.585281759040384!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bccb1279b19e03%3A0x4189fef021d7ace8!2z6Zi_5qC55bu35bed6aaZ6Zaj!5e0!3m2!1szh-TW!2stw!4v1716957943106!5m2!1szh-TW!2stw" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
</body>

HaveFun_03/Views/TIM03/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h5>TIM03</h5>

HaveFun_03/Views/TIM05/Index.cshtml
<h1>HI!5號ㄉ</h1>

HaveFun_03/Views/TIM07/Index.cshtml
<div>TIM07</div>

HaveFun_03/Views/TIM08/Index.cshtml
TIM08

HaveFun_03/Views/Tim04/Index.cshtml
<h1>TIM04</h1>